[package]
name = "doscenario-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.26"
hyper = "0.14.24"
log = "0.4.17"
tonic = "0.8.3"
tower = "0.4.13"
urlencoding = "2.1.2"
